project:
  type: website
  output-dir: docs

website:
  title: "HA"
  favicon: assets/images/favicon.png
  back-to-top-navigation: false
  navbar:
    search: false
    toggle-position: "right"
    tools-collapse: true
    right:
      # - text: Home
      #   href: index.qmd
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
  page-footer: 
    left: "{{< iconify fa6-regular:copyright >}} CC-by Hassen Allegue"
    center: "This webite is built with <a href='https://quarto.org/' target='_blank'>Quarto</a> using the theme <a href='https://bootswatch.com/flatly/' target='_blank'>Flatly</a> and <a href='https://bootswatch.com/darkly/' target='_blank'>Darkly</a>"
    right: 
      - text: "{{< iconify fa6-brands:github >}}"
        href: https://github.com/hallegue
        target: "_blank"
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/hallegue.bsky.social
        target: "_blank"
      - text: "{{< iconify fa6-brands:orcid >}}"
        href: https://orcid.org/0000-0001-9357-9151
        target: "_blank"
      - text: "{{< iconify fa6-brands:researchgate >}}"
        href: https://www.researchgate.net/profile/Hassen-Allegue
        target: "_blank"
      - text: "{{< iconify fa6-brands:google-scholar >}}"
        href: https://scholar.google.co.in/citations?hl=en&user=fRjVzY4AAAAJ
        target: "_blank"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

